#!/usr/bin/env python3
"""
scripts/maintenance/setup_data_tree.py  --  Monzia Moodie

Idempotent, NON-DESTRUCTIVE setup of the canonical data/ skeleton from
configs/data_manifest.yaml. Creates only what is missing; never deletes, moves,
or overwrites data. Safe to re-run.

What it does:
  * creates data/{external,raw,raw/cache,processed,reference,interim,splits}
  * drops a track-the-dir .gitignore ("*" + "!.gitignore") in each subtree
    (matches the repo's existing convention) -- only if absent
  * with --scaffold-sources: also creates an empty dir per manifest source
  * emits configs/rclone_data_filter.txt from the manifest (sources with
    sync=true AND tier!=controlled are included; everything else excluded) --
    overwrites only that generated file, and refuses if a controlled source is
    marked sync=true (compliance gate)

Usage:
  python scripts/maintenance/setup_data_tree.py            # skeleton + .gitignores + filter
  python scripts/maintenance/setup_data_tree.py --scaffold-sources
  python scripts/maintenance/setup_data_tree.py --dry-run  # print actions, write nothing
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

_SUBTREES = ["external", "raw", "raw/cache", "processed", "reference", "interim", "splits"]
# reference/ holds small TRACKED schemas/manifests -- it must NOT be ignore-all.
_TRACKED_SUBTREES = {"reference"}
_GITIGNORE = "# Ignore all data files -- directory tracked by this file\n*\n!.gitignore\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-dir", default="data", type=Path)
    ap.add_argument("--manifest", default="configs/data_manifest.yaml", type=Path)
    ap.add_argument("--filter-out", default="configs/rclone_data_filter.txt", type=Path)
    ap.add_argument("--scaffold-sources", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    if not args.manifest.exists():
        print(f"[ABORT] manifest not found: {args.manifest}")
        return 2
    man = yaml.safe_load(args.manifest.read_text(encoding="utf-8"))
    sources = man.get("sources", {})

    # compliance gate BEFORE writing anything
    bad = [s for s, m in sources.items() if m.get("sync") and m.get("tier") == "controlled"]
    if bad:
        print(f"[ABORT] controlled sources marked sync=true: {bad}. Fix the manifest first.")
        return 2

    def do(msg):
        print(("  [dry] " if args.dry_run else "  [ok] ") + msg)

    # subtrees + their .gitignore
    for sub in _SUBTREES:
        d = args.data_dir / sub
        if not d.exists():
            do(f"mkdir {d}")
            if not args.dry_run:
                d.mkdir(parents=True, exist_ok=True)
        if sub in _TRACKED_SUBTREES:
            continue  # tracked-content subtree: do not write an ignore-all .gitignore
        gi = d / ".gitignore"
        if not gi.exists():
            do(f"write {gi}")
            if not args.dry_run:
                gi.write_text(_GITIGNORE, encoding="utf-8")

    # optional per-source dirs
    if args.scaffold_sources:
        for canon, meta in sources.items():
            loc = meta.get("location", "external")
            d = args.data_dir / loc / canon
            if not d.exists():
                do(f"mkdir source {d}")
                if not args.dry_run:
                    d.mkdir(parents=True, exist_ok=True)

    # rclone filter from the manifest
    lines = ["# generated by setup_data_tree.py from configs/data_manifest.yaml",
             "# included = sync:true AND tier!=controlled; everything else excluded",
             "# usage: rclone sync data/ <remote>:<base> --filter-from this_file"]
    for canon, meta in sorted(sources.items()):
        if meta.get("sync") and meta.get("tier") != "controlled":
            loc = meta.get("location", "external")
            lines.append(f"+ /{loc}/{canon}/**")
    lines.append("- *")
    filt = "\n".join(lines) + "\n"
    do(f"write {args.filter_out} ({sum(1 for l in lines if l.startswith('+'))} included sources)")
    if not args.dry_run:
        args.filter_out.parent.mkdir(parents=True, exist_ok=True)
        args.filter_out.write_text(filt, encoding="utf-8")

    print("  [done] " + ("dry-run (nothing written)" if args.dry_run else "data skeleton ready"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
