"""The final v4/schema3 epoch, frozen before its retirement.

Phase 1C Unit 3A++.0. Created 2026-09-02.

WHAT THIS CORPUS IS FOR
-----------------------
`tests/fixtures/provenance_migration_v1/` answers:

    Did relocating canonical ownership change identity semantics?

This one answers a different question:

    Exactly what did the final v4/schema3 implementation emit before it was
    retired?

Unit 3A++.2 will deliberately migrate source evidence from `v4/schema3` to
`v5/schema5`. That migration is AUTHORIZED to change the domain, the embedded
schema version and the resulting evidence digest -- and NOT authorized to
change the dependency set, dependency order, source keys, source identities,
roles, coordinate contexts, release identifiers or artifact digests.

Without a frozen record of the old epoch, "only the authorized things changed"
is unprovable. With one, it is a differential test.

THE HISTORICAL CONDITION IS PRESERVED, NOT CLEANED
--------------------------------------------------
MEASURED 2026-09-02 in `provenance/source.py`: the domain reads
`drift-source-evidence-manifest-v4` while the payload it digests carries
`"schema_version": 3`. `product` was added on 2026-09-01, changing key
equality AND the record shape; the domain was bumped and the literal was not.

Two writable declarations represented one semantic version, which permits
divergence by construction. The corpus records that so a future reader can
determine why v4 emitted schema 3, why v5 exists, and why the digest differs --
without archaeology.

WHY CANONICAL JSON RATHER THAN PICKLE
-------------------------------------
MEASURED: five runs under `PYTHONHASHSEED=random` produce byte-identical
output, because `SourceDependency.as_record` returns
`sorted(r.value for r in self.roles)` and `SourceEvidenceManifest.of` sorts
dependencies. No set iteration order reaches the record.

The migration corpus needed `PYTHONHASHSEED=0` precisely because it pickles a
frozenset of a string-based enum. Pickle is the right oracle for old
fully-qualified class locations; a stable canonical representation is the right
oracle for semantic identity.

Acronyms: SHA-256 = Secure Hash Algorithm 256-bit; JSON = JavaScript Object
Notation.

Author: Monzia Moodie
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from genomic_variant_classifier.provenance import (
    EVIDENCE_DOMAIN,
    canonical_json,
    domain_digest,
)

_FIX = (Path(__file__).resolve().parents[2] / "tests" / "fixtures"
        / "source_evidence_epoch_v4" / "epoch.json")

pytestmark = pytest.mark.skipif(
    not _FIX.is_file(),
    reason="the v4 epoch corpus is absent; it is generated by "
           "scripts/dev/freeze_source_evidence_epoch.py and MUST be present "
           "in the repository -- this must not skip in CI")


def _doc() -> dict:
    return json.loads(_FIX.read_text(encoding="utf-8"))


def _names() -> list:
    return sorted(_doc()["cases"]) if _FIX.is_file() else []


# ---------------------------------------------------------------------------
# 1. the corpus records the epoch it claims to
# ---------------------------------------------------------------------------

def test_the_corpus_declares_the_v4_epoch():
    d = _doc()
    assert d["identity_family"] == "source_evidence_manifest"
    assert d["domain"] == "drift-source-evidence-manifest-v4"
    assert d["embedded_schema_version"] == 3
    assert d["case_count"] == len(d["cases"]) == 13


def test_the_HISTORICAL_DEFECT_is_recorded_not_cleaned():
    """Section 10: turn the historical defect into evidence.

    A future engineer must be able to determine why v4 emitted schema 3
    without archaeology.
    """
    d = _doc()
    condition = d["known_historical_condition"]
    assert "differ" in condition
    assert "schema_version" in condition
    assert "two writable declarations" in condition.lower()
    assert d["domain"].endswith("-v4")
    assert d["embedded_schema_version"] == 3
    for case in d["cases"].values():
        assert case["canonical_record"]["schema_version"] == 3


def test_the_corpus_records_a_RETIRED_epoch():
    """INVERTED at Phase 1C Unit 3A++.2, exactly as this file anticipated.

    Before that unit this read `EVIDENCE_DOMAIN == _doc()["domain"]`, with the
    note that "after 3A++.2 this assertion must be INVERTED by that unit,
    which is precisely how the corpus proves the migration happened rather
    than assuming it."

    It has been. The corpus now records a RETIRED epoch, and that is its
    purpose: v4 keeps meaning what v4 historically meant.
    """
    assert EVIDENCE_DOMAIN != _doc()["domain"], (
        "the live domain still equals the frozen one; the v5 migration did "
        "not happen, and this corpus is not yet a historical record")
    assert _doc()["domain"] == "drift-source-evidence-manifest-v4"
    assert EVIDENCE_DOMAIN == "drift-source-evidence-manifest-v5"


# ---------------------------------------------------------------------------
# 2. every digest is REDERIVABLE from its own frozen record
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name", _names())
def test_the_frozen_digest_derives_from_the_frozen_RECORD(name):
    """The strongest property this corpus has.

    The digest is not merely stored beside the record -- it is REPRODUCED from
    it, so an edited record cannot keep a stale digest and pass.
    """
    case = _doc()["cases"][name]
    assert domain_digest(_doc()["domain"], case["canonical_record"]) \
        == case["digest"]


@pytest.mark.parametrize("name", _names())
def test_the_record_is_CANONICAL_json(name):
    """Re-serialising must reproduce the same bytes, at any nesting depth."""
    case = _doc()["cases"][name]
    once = canonical_json(case["canonical_record"])
    twice = canonical_json(json.loads(once.decode("ascii")))
    assert once == twice


# ---------------------------------------------------------------------------
# 3. the scientific laws the corpus demonstrates
# ---------------------------------------------------------------------------

def test_LAW_III_a_release_change_alters_identity():
    """`same_key_different_release` shares an identity with `clinvar_grch38`,
    so it digests identically. The contrast case, at release 2026-09, must
    not."""
    c = _doc()["cases"]
    assert c["same_key_different_release"]["digest"] == c["clinvar_grch38"]["digest"]
    assert c["_contrast_same_key_later_release"]["digest"] != c["clinvar_grch38"]["digest"]
    a = c["clinvar_grch38"]["identities"][0]
    b = c["_contrast_same_key_later_release"]["identities"][0]
    assert a["key"] == b["key"], "the premise: one key"
    assert a["release_id"] != b["release_id"]


def test_LAW_IV_a_coordinate_context_change_alters_identity():
    c = _doc()["cases"]
    assert c["clinvar_grch37"]["digest"] != c["clinvar_grch38"]["digest"]
    a = c["clinvar_grch38"]["identities"][0]
    b = c["clinvar_grch37"]["identities"][0]
    assert a["key"] == b["key"] and a["release_id"] == b["release_id"]
    assert a["coordinate_context"] != b["coordinate_context"]


def test_LAW_V_different_bytes_are_a_different_identity():
    c = _doc()["cases"]
    assert c["same_key_different_digest"]["digest"] != c["clinvar_grch38"]["digest"]
    a = c["clinvar_grch38"]["identities"][0]
    b = c["same_key_different_digest"]["identities"][0]
    assert a["key"] == b["key"] and a["release_id"] == b["release_id"]
    assert a["coordinate_context"] == b["coordinate_context"]
    assert a["artifact_sha256"] != b["artifact_sha256"]


def test_a_build_independent_source_carries_no_fake_assembly():
    ctx = _doc()["cases"]["build_independent_source"]["identities"][0][
        "coordinate_context"]
    assert ctx["identifier"] in (None, ""), ctx
    assert ctx != _doc()["cases"]["clinvar_grch38"]["identities"][0][
        "coordinate_context"]


def test_the_three_GENCODE_products_are_three_digests():
    c = _doc()["cases"]
    digests = {c[n]["digest"] for n in ("gencode_transcripts",
                                       "gencode_pc_transcripts",
                                       "gencode_lncrna_transcripts")}
    assert len(digests) == 3
    keys = [c[n]["identities"][0]["key"] for n in ("gencode_transcripts",
                                                   "gencode_pc_transcripts",
                                                   "gencode_lncrna_transcripts")]
    assert len({k["product"] for k in keys}) == 3
    assert len({k["source"] for k in keys}) == 1


def test_EVERY_role_subset_serialises_sorted():
    """The property, not the sample.

    MEASURED BY SABOTAGE 2026-09-02: replacing
    `sorted(r.value for r in self.roles)` with an unsorted comprehension
    changed NO test -- even under a FIXED hash seed -- because the corpus uses
    `{observation, label}`, one of only three subsets of five roles whose
    natural iteration order happens to equal its sorted order.

    MEASURED across seeds 0, 1, 7 and 42: between TWENTY and TWENTY-THREE of
    the twenty-six non-trivial subsets iterate unsorted. Asserting the
    property over every subset cannot depend on which one a fixture chose.
    """
    import itertools

    from genomic_variant_classifier.provenance import (
        ArtifactKind, CoordinateContext, SourceArtifactIdentity,
        SourceArtifactKey, SourceDependency, SourceRole)

    identity = SourceArtifactIdentity(
        key=SourceArtifactKey("clinvar", ArtifactKind.PRIMARY_RELEASE),
        release_id="2026-08",
        coordinate_context=CoordinateContext.assembly("GRCh38"),
        artifact_sha256=hashlib.sha256(b"role-subset-probe").hexdigest())

    roles = list(SourceRole)
    checked = 0
    for size in range(1, len(roles) + 1):
        for combo in itertools.combinations(roles, size):
            dep = SourceDependency(identity=identity,
                                   roles=frozenset(combo))
            got = dep.as_record()["roles"]
            checked += 1
            assert got == sorted(got), (combo, got)
            assert got == sorted(r.value for r in combo), (combo, got)
    assert checked == 2 ** len(roles) - 1 == 31


def test_roles_are_SORTED_in_the_canonical_record():
    """Set iteration order must not reach identity.

    This is why the corpus needs no PYTHONHASHSEED pin, and the reason it can
    be canonical JSON rather than pickle bytes.
    """
    roles = _doc()["cases"]["multiple_source_roles"][
        "canonical_record"]["dependencies"][0]["roles"]
    assert len(roles) == 2
    assert roles == sorted(roles), roles


def test_dependency_ORDER_is_canonical_not_caller_supplied():
    for name in ("multiple_sources", "genomic_and_build_independent",
                 "same_source_different_products"):
        order = _doc()["cases"][name]["dependency_order"]
        assert order == sorted(order), (name, order)


# ---------------------------------------------------------------------------
# 4. THE DIFFERENTIAL ORACLE -- live code vs the frozen epoch
# ---------------------------------------------------------------------------

def _generator():
    """Load the committed freeze script and return its module.

    The test calls the SAME `build()` the fixture was written by, so the two
    cannot drift apart. Re-implementing the case construction here would
    reproduce the `_semantic`/`_semantic_of` hazard: two projections that agree
    today and silently diverge later.
    """
    import importlib.util
    import sys

    path = (Path(__file__).resolve().parents[2] / "scripts" / "dev"
            / "freeze_source_evidence_epoch.py")
    if not path.is_file():                                  # pragma: no cover
        pytest.skip("the freeze script is absent: {}".format(path))
    spec = importlib.util.spec_from_file_location("_epoch_freeze", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["_epoch_freeze"] = mod
    argv = sys.argv
    sys.argv = ["_epoch_freeze"]
    try:
        spec.loader.exec_module(mod)
    finally:
        sys.argv = argv
        sys.modules.pop("_epoch_freeze", None)
    return mod


def test_the_freeze_script_REFUSES_to_rebuild_a_retired_epoch():
    """The differential oracle, inverted at 3A++.2.

    Before that unit this regenerated the corpus and asserted byte equality,
    with the note that a deliberate migration "must update the differential
    test explicitly -- not regenerate this corpus silently."

    The freeze script has its OWN guard for this: `build()` compares the live
    `EVIDENCE_DOMAIN` against the epoch it freezes and raises rather than
    emitting a corpus mislabelled as v4. That refusal is now the assertion --
    a stronger one, because it is enforced by the script itself rather than by
    a test remembering to check.
    """
    with pytest.raises(RuntimeError) as exc:
        _generator().build()
    message = str(exc.value)
    assert "drift-source-evidence-manifest-v5" in message
    assert "drift-source-evidence-manifest-v4" in message
    assert "BEFORE the migration to v5" in message


def test_the_frozen_digests_no_longer_match_the_LIVE_ones():
    """Named per case, so a reader sees WHICH cases moved -- all of them.

    Rebuilding each frozen case and re-digesting it under the live v5 epoch
    must differ from the recorded v4 digest. `test_source_evidence_epoch_v5.py`
    proves that ONLY the epoch metadata changed; this proves the digest did.
    """
    from genomic_variant_classifier.provenance import (
        ArtifactKind, CoordinateContext, CoordinateContextKind,
        SourceArtifactIdentity, SourceArtifactKey, SourceDependency,
        SourceEvidenceManifest, SourceRole)

    frozen = _doc()
    unchanged = []
    for name, case in sorted(frozen["cases"].items()):
        deps = []
        for dep in case["canonical_record"]["dependencies"]:
            rec = dep["identity"]
            ctx = rec["coordinate_context"]
            context = (
                CoordinateContext.assembly(ctx["identifier"])
                if CoordinateContextKind(ctx["kind"])
                is CoordinateContextKind.GENOMIC_ASSEMBLY
                else CoordinateContext.build_independent())
            key = rec["key"]
            deps.append(SourceDependency(
                identity=SourceArtifactIdentity(
                    key=SourceArtifactKey(key["source"],
                                          ArtifactKind(key["artifact_kind"]),
                                          key["product"] or None),
                    release_id=rec["release_id"],
                    coordinate_context=context,
                    artifact_sha256=rec["artifact_sha256"]),
                roles=frozenset(SourceRole(r) for r in dep["roles"])))
        if SourceEvidenceManifest.of(tuple(deps)).digest == case["digest"]:
            unchanged.append(name)
    assert not unchanged, (
        "these cases still digest to their v4 value: {}".format(unchanged))


# ---------------------------------------------------------------------------
# 5. the file itself
# ---------------------------------------------------------------------------

def test_the_corpus_file_is_byte_stable_and_ascii():
    raw = _FIX.read_bytes()
    assert raw.endswith(b"\n")
    assert b"\r\n" not in raw
    assert all(b < 128 for b in raw), "the corpus must be pure ASCII"
    assert hashlib.sha256(raw).hexdigest() == hashlib.sha256(
        _FIX.read_bytes()).hexdigest()


def test_every_case_records_all_SEVEN_frozen_facts():
    """Section 9 names what must be frozen."""
    for name, case in _doc()["cases"].items():
        for field in ("canonical_record", "digest", "dependency_order",
                      "keys_in_order", "identities"):
            assert field in case, (name, field)
        assert len(case["identities"]) == len(case["dependency_order"])
        assert len(case["keys_in_order"]) == len(case["identities"])
        for k in case["keys_in_order"]:
            assert len(k) == 3, "canonical_key is a THREE-field tuple"
