"""The frozen answer to what a scientific identity MEANS, before its owner moves.

Phase 1C Unit 3A.0. Created 2026-09-02.

WHY A FROZEN CORPUS
-------------------
Unit 3A moves canonical ownership of the identity substrate from
`monitoring.drift` into `provenance`. Its governing invariant is:

    UNIT 3A MAY CHANGE WHERE A SCIENTIFIC IDENTITY IS DEFINED.
    IT MUST NOT CHANGE WHAT THAT IDENTITY MEANS.

An invariant checked only against post-move code proves nothing, because the
post-move code agrees with itself. These fixtures were generated from the
PRE-MOVE tree at 4805033 and committed, so afterwards they are an independent
witness rather than a restatement.

THREE ORACLES, WHICH FAIL FOR DIFFERENT REASONS
-----------------------------------------------
BEHAVIOURAL   the existing suite -- every prior node identity still passes
SEMANTIC      `semantic.json` -- canonical keys, records, digests, describes
PERSISTENCE   the pickles -- old bytes still resolve to the canonical classes

A single implementation defect rarely trips all three, and a defect that trips
none is not a defect this migration can cause.

AND ONE FILE THAT MUST CHANGE
-----------------------------
`ownership.json` records `__module__.__qualname__` per entry. It is the ONE
thing Unit 3A is meant to alter, so it is deliberately kept OUT of
`semantic.json`. Before the move every entry reads `monitoring.drift.*`; after
it, every entry must read `provenance.*`. `test_ownership_is_recorded_as_the_
PRE_MOVE_state` pins the baseline so a later unit can prove the move happened
rather than assuming it.

WHY PERSISTENCE MATTERS HERE SPECIFICALLY
-----------------------------------------
The 2026-09-02 census found no tracked file containing BOTH a serialization
mechanism and one of these types. That establishes no DIRECT STATIC coupling.
It does NOT establish that no persisted object graph contains one: a
`TrainingState` holding a `SourceManifest` in one module, pickled by
`joblib.dump` in another, is invisible to same-file co-occurrence.

This repository has already paid for a class relocation once --
`scripts/migrate_pickles.py` exists, and `variant_ensemble.py` sets
`_CNN1DModule.__module__` explicitly with a test asserting it, after a recorded
cross-platform unpickle failure.

Acronyms: SHA-256 = Secure Hash Algorithm 256-bit; JSON = JavaScript Object
Notation.

Author: Monzia Moodie
"""
from __future__ import annotations

import json
import pickle
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
_FIX = _ROOT / "tests" / "fixtures" / "provenance_migration_v1"

_INDEX = _FIX / "index.json"
_SEMANTIC = _FIX / "semantic.json"
_OWNERSHIP = _FIX / "ownership.json"

pytestmark = pytest.mark.skipif(
    not _INDEX.is_file(),
    reason="the migration corpus is absent; it is generated by "
           "scripts/dev/build_provenance_migration_fixtures.py and MUST be "
           "present in the repository -- this must not skip in CI",
)


def _index() -> dict:
    return json.loads(_INDEX.read_text(encoding="utf-8"))


def _names() -> list[str]:
    return sorted(_index()["entries"])


def _load(name: str):
    return pickle.loads((_FIX / (name + ".pickle")).read_bytes())


def _semantic_of(obj) -> dict:
    """The SAME projection the generator used. Kept in step by a test below."""
    out = {"type_name": type(obj).__name__}
    for attr in ("canonical_key", "digest", "evidence_digest"):
        if hasattr(obj, attr):
            value = getattr(obj, attr)
            out[attr] = list(value) if isinstance(value, tuple) else value
    for meth in ("as_record", "describe"):
        if hasattr(obj, meth):
            out[meth] = getattr(obj, meth)()
    return out


# ---------------------------------------------------------------------------
# 1. the corpus exists and covers the boundary cases it claims
# ---------------------------------------------------------------------------

def test_the_corpus_is_present_and_complete():
    idx = _index()
    assert idx["schema"] == 1
    entries = idx["entries"]
    assert len(entries) == 16, sorted(entries)
    for name, meta in entries.items():
        p = _FIX / meta["pickle"]
        assert p.is_file(), name
        assert p.stat().st_size == meta["pickle_bytes"], name


def test_every_pickle_matches_its_recorded_digest():
    """A fixture edited by hand is not a witness."""
    import hashlib
    for name, meta in _index()["entries"].items():
        blob = (_FIX / meta["pickle"]).read_bytes()
        assert hashlib.sha256(blob).hexdigest() == meta["pickle_sha256"], name


@pytest.mark.parametrize("name", [
    "key_gencode_transcripts",
    "key_gencode_pc_transcripts",
    "key_gencode_lncrna_transcripts",
    "coordinate_build_independent",
    "coordinate_grch37",
    "coordinate_grch38",
    "identity_uniprot_build_independent",
    "dependency_multi_role",
    "evidence_three_gencode_products",
    "evidence_multi_authority",
    "manifest_clinvar",
    "transformation_all_component_kinds",
])
def test_the_corpus_covers_the_BOUNDARY_cases(name):
    """Not happy paths. Each of these exists because it can break alone."""
    assert name in _index()["entries"]


# ---------------------------------------------------------------------------
# 2. ORACLE C -- old bytes load
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name", _names() if _INDEX.is_file() else [])
def test_every_pre_move_pickle_still_LOADS(name):
    obj = _load(name)
    assert obj is not None


@pytest.mark.parametrize("name", _names() if _INDEX.is_file() else [])
def test_a_loaded_object_EQUALS_itself_reloaded(name):
    """Equality must survive the round trip, not merely construction."""
    assert _load(name) == _load(name)
    assert hash(_load(name)) == hash(_load(name))


# ---------------------------------------------------------------------------
# 3. ORACLE B -- meaning is unchanged
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name", _names() if _INDEX.is_file() else [])
def test_the_SEMANTIC_projection_is_unchanged(name):
    """canonical_key, as_record, digest, describe -- all frozen pre-move.

    If relocation alters canonical ordering, a domain string, a field name or
    a sort, this fails. That is the whole purpose of the file.
    """
    frozen = json.loads(_SEMANTIC.read_text(encoding="utf-8"))[name]
    assert _semantic_of(_load(name)) == frozen


def test_the_projection_here_matches_the_GENERATOR():
    """The oracle is worthless if the two projections drift apart.

    `semantic.json` was written by `_semantic` in the generator; this file
    re-implements it as `_semantic_of`. If they diverge, the comparison above
    silently starts testing something else -- so every recorded key must be
    produced here for at least one entry.
    """
    frozen = json.loads(_SEMANTIC.read_text(encoding="utf-8"))
    recorded_keys = set()
    for entry in frozen.values():
        recorded_keys |= set(entry)
    produced = set()
    for name in _names():
        produced |= set(_semantic_of(_load(name)))
    assert recorded_keys == produced, (recorded_keys ^ produced)


def test_the_three_GENCODE_products_remain_three_identities():
    keys = [tuple(json.loads(_SEMANTIC.read_text(encoding="utf-8"))[n]
                  ["canonical_key"])
            for n in ("key_gencode_transcripts", "key_gencode_pc_transcripts",
                      "key_gencode_lncrna_transcripts")]
    assert len(set(keys)) == 3, keys


def test_build_independent_is_NOT_a_missing_assembly():
    """`None` would confound 'no coordinate system' with 'not recorded'."""
    obj = _load("coordinate_build_independent")
    assert obj.identifier is None
    # is_genomic is a PROPERTY, not a method. Calling it returned a bool and
    # then tried to CALL that bool -- caught by running the test rather than
    # by reading an AST listing that showed the name without its decorator.
    assert obj.is_genomic is False
    assert _load("coordinate_grch38").is_genomic is True
    assert obj != _load("coordinate_grch38")


# ---------------------------------------------------------------------------
# 4. the file that MUST change
# ---------------------------------------------------------------------------

def test_ownership_is_recorded_as_the_PRE_MOVE_state():
    """Kept OUT of semantic.json deliberately.

    `__module__` is the ONE thing Unit 3A changes, so including it in the
    semantic oracle would make that oracle fail by construction and prove
    nothing. Recording it separately lets a later unit prove the move HAPPENED.
    """
    own = json.loads(_OWNERSHIP.read_text(encoding="utf-8"))
    assert len(own) == 16
    assert all(v.startswith("genomic_variant_classifier.monitoring.drift.")
               for v in own.values()), own


def test_semantic_json_carries_NO_module():
    frozen = json.loads(_SEMANTIC.read_text(encoding="utf-8"))
    assert not any("module" in e for e in frozen.values())
