"""Tests for fail-closed requirements parsing -- MEASUREMENT-INTEGRITY-1.

Author: Monzia Moodie
"""
from __future__ import annotations

import io
import sys
import tempfile
from pathlib import Path

import pytest

from genomic_variant_classifier.deps.requirements_parse import (
    DirectiveKind, MeasurementIntegrityError, ParseAudit, ParsedRequirement,
    direct_requirements, parse_requirements_file,
)


def _write(text: str, name: str = "r.txt", *, binary: bool = False) -> Path:
    d = Path(tempfile.mkdtemp())
    p = d / name
    if binary:
        open(p, "wb").write(text)
    else:
        io.open(p, "w", encoding="utf-8", newline="\n").write(text)
    return p


HASHED = """#
# This file is autogenerated by pip-compile with Python 3.12
#
aiobotocore==3.6.0 \\
    --hash=sha256:78e6b95b258bcdde8d681d6851f88f337ed30b2d6611fae45366e6bf7488feb3 \\
    --hash=sha256:bf1c2e1d8492d98c9b63b330723a44b41a5d402afd19eaca704e107b91669c09
    # via s3fs
anyio==4.13.0 \\
    --hash=sha256:aaaaaaaabbbbbbbbccccccccddddddddeeeeeeeeffffffff0000000011111111
"""


# ---- THE FAILURE THIS MODULE EXISTS FOR --------------------------------
def test_a_hashed_lock_parses_instead_of_reporting_zero():
    r = parse_requirements_file(_write(HASHED, "x.lock"))
    assert set(r.clauses) == {"aiobotocore", "anyio"}
    assert r.clauses["aiobotocore"][0].specifier == "==3.6.0"
    assert r.audit.joined_continuations == 3
    assert r.audit.reconciles()


def test_CRLF_continuations_join_under_a_NON_translating_reader():
    """MEASURED: `raw.replace("\\\\\\n", " ")` joins ZERO records when the file
    is read with newline="" -- the same zero-record failure this module ends.
    The regex matches CRLF, LF and CR."""
    raw = (b"aiobotocore==3.6.0 \\\r\n    --hash=sha256:aaa \\\r\n"
           b"    --hash=sha256:bbb\r\nanyio==4.13.0\r\n")
    r = parse_requirements_file(_write(raw, "crlf.lock", binary=True))
    assert set(r.clauses) == {"aiobotocore", "anyio"}
    assert r.audit.joined_continuations == 2


def test_zero_parsed_from_nonzero_records_RAISES():
    with pytest.raises(MeasurementIntegrityError) as exc:
        parse_requirements_file(_write("this is not a requirement at all\n"))
    assert "INSTRUMENT FAILURE" in str(exc.value)


def test_a_rejected_record_RAISES_by_default():
    with pytest.raises(MeasurementIntegrityError) as exc:
        parse_requirements_file(_write("numpy>=1.26\n!!!broken!!!\n"))
    assert "rejected" in str(exc.value)


def test_a_rejected_record_can_be_TOLERATED_explicitly():
    r = parse_requirements_file(_write("numpy>=1.26\n!!!broken!!!\n"),
                                allow_failures=True)
    assert set(r.clauses) == {"numpy"}
    assert len(r.audit.parse_failures) == 1


# ---- A. duplicate clauses ----------------------------------------------
def test_TWO_CLAUSES_for_one_distribution_are_both_kept():
    """A dict of one record per package cannot represent a marker-split
    declaration. Overwriting discards a whole branch of the contract."""
    r = parse_requirements_file(_write(
        'foo==1.2 ; python_version < "3.12"\n'
        'foo==2.0 ; python_version >= "3.12"\n'))
    assert set(r.clauses) == {"foo"}
    assert len(r.clauses["foo"]) == 2
    assert {c.specifier for c in r.clauses["foo"]} == {"==1.2", "==2.0"}
    assert {c.marker for c in r.clauses["foo"]} == {
        'python_version < "3.12"', 'python_version >= "3.12"'}


def test_a_single_clause_is_still_a_tuple():
    r = parse_requirements_file(_write("numpy>=1.26\n"))
    assert isinstance(r.clauses["numpy"], tuple)
    assert len(r.clauses["numpy"]) == 1


# ---- B. canonical distribution identity --------------------------------
@pytest.mark.parametrize("raw,canonical", [
    ("foo_bar>=1", "foo-bar"),
    ("foo.bar>=1", "foo-bar"),
    ("PyBigWig>=0.3.25", "pybigwig"),
    ("zope.interface>=5", "zope-interface"),
    ("backports_abc>=0.5", "backports-abc"),
])
def test_names_use_the_SHARED_canonicaliser(raw, canonical):
    """Measured with packaging 26.0: a naive .lower() disagrees on six of ten
    sampled names. Identity is owned by model.DistributionName."""
    r = parse_requirements_file(_write(raw + "\n"))
    assert canonical in r.clauses


# ---- C. typed directives -----------------------------------------------
def test_an_include_is_an_EDGE_not_an_anonymous_option():
    """`-r requirements.in` is how requirements-dev.in pulls in the production
    set. Counting it beside --index-url discards the topology."""
    r = parse_requirements_file(_write(
        "-r requirements.in\n-c constraints.txt\n--index-url https://x\n"
        "-e .\nnumpy>=1.26\n"))
    kinds = [d.kind for d in r.directives]
    assert DirectiveKind.REQUIREMENT_INCLUDE in kinds
    assert DirectiveKind.CONSTRAINT_INCLUDE in kinds
    assert DirectiveKind.INDEX_URL in kinds
    assert DirectiveKind.EDITABLE in kinds
    includes = r.includes()
    assert {d.argument for d in includes} == {"requirements.in", "constraints.txt"}


def test_directive_arguments_are_preserved():
    r = parse_requirements_file(_write("-r requirements.in\nnumpy>=1.26\n"))
    assert r.directives[0].argument == "requirements.in"
    assert r.directives[0].kind is DirectiveKind.REQUIREMENT_INCLUDE


def test_an_unknown_option_is_OTHER_not_a_parse_failure():
    r = parse_requirements_file(_write("--no-binary :all:\nnumpy>=1.26\n"))
    assert r.directives[0].kind is DirectiveKind.OTHER
    assert not r.audit.parse_failures


# ---- D. hashes preserved -----------------------------------------------
def test_hashes_are_RETAINED_not_merely_stripped():
    """These are supply-chain reference artifacts. Discarding the integrity
    material loses the distinction between "same version" and "same version and
    same bytes"."""
    r = parse_requirements_file(_write(HASHED, "x.lock"))
    assert len(r.clauses["aiobotocore"][0].hashes) == 2
    assert r.clauses["aiobotocore"][0].hashes[0].startswith("sha256:")
    assert len(r.clauses["anyio"][0].hashes) == 1


def test_an_unhashed_record_has_no_hashes():
    r = parse_requirements_file(_write("numpy>=1.26\n"))
    assert r.clauses["numpy"][0].hashes == ()


# ---- 5. no cross-type equality ------------------------------------------
def test_a_record_does_NOT_compare_equal_to_a_bare_specifier():
    """That comparison discards name and marker by design, and would let a
    marker-sensitive object pass a specifier-only assertion."""
    r = parse_requirements_file(_write("numpy>=1.26\n"))
    rec = r.clauses["numpy"][0]
    assert rec != ">=1.26"
    assert rec.specifier == ">=1.26"


def test_records_differing_only_by_MARKER_are_not_equal():
    a = ParsedRequirement(name="pybigwig", specifier=">=0.3.25")
    b = ParsedRequirement(name="pybigwig", specifier=">=0.3.25",
                          marker='sys_platform != "win32"')
    assert a != b


# ---- markers ------------------------------------------------------------
def test_a_platform_marker_is_stored():
    r = parse_requirements_file(_write(
        'pyBigWig>=0.3.25; sys_platform != "win32"\n'))
    rec = r.clauses["pybigwig"][0]
    assert rec.marker == 'sys_platform != "win32"'
    assert rec.specifier == ">=0.3.25"


def test_an_unconditional_record_has_no_marker():
    r = parse_requirements_file(_write("numpy>=1.26\n"))
    assert r.clauses["numpy"][0].marker is None


# ---- audit --------------------------------------------------------------
def test_comments_and_blanks_are_counted_not_silently_dropped():
    r = parse_requirements_file(_write("# header\n\nnumpy>=1.26\n\n# trailing\n"))
    assert set(r.clauses) == {"numpy"}
    assert r.audit.ignored_comments == 2
    assert r.audit.ignored_blank == 2


def test_the_parse_reconciles_against_the_PHYSICAL_file():
    text = ("# autogenerated\n"
            "aiobotocore==3.6.0 \\\n    --hash=sha256:aaa \\\n    --hash=sha256:bbb\n"
            "\n"
            "anyio==4.13.0\n")
    r = parse_requirements_file(_write(text, "x.lock"))
    a = r.audit
    assert a.physical_lines == (a.ignored_comments + a.ignored_blank
                                + a.logical_records + a.joined_continuations)
    assert a.joined_continuations == 2


def test_the_physical_reconciliation_actually_FIRES_on_a_lost_line():
    """The guard must be shown to fail, or it proves nothing."""
    from genomic_variant_classifier.deps import requirements_parse as rp
    real = rp.ParseAudit

    class _LosesALine(real):
        def __new__(cls, **kw):
            kw["physical_lines"] = kw.get("physical_lines", 0) + 1
            return real(**kw)

    rp.ParseAudit = _LosesALine
    try:
        with pytest.raises(MeasurementIntegrityError) as exc:
            rp.parse_requirements_file(_write("numpy>=1.26\n"))
        assert "never classified" in str(exc.value)
    finally:
        rp.ParseAudit = real


def test_an_empty_file_is_an_answer_not_a_failure():
    r = parse_requirements_file(_write("# only a comment\n"))
    assert r.clauses == {}
    assert r.audit.logical_records == 0


def test_the_audit_is_immutable():
    import dataclasses
    r = parse_requirements_file(_write("numpy>=1.26\n"))
    try:
        r.audit.parsed_requirements = 999
    except dataclasses.FrozenInstanceError:
        return
    raise AssertionError("the parse audit was mutable")


def test_a_parsed_requirement_is_immutable():
    import dataclasses
    r = parse_requirements_file(_write("numpy>=1.26\n"))
    try:
        r.clauses["numpy"][0].specifier = ">=999"
    except dataclasses.FrozenInstanceError:
        return
    raise AssertionError("a parsed requirement was mutable")


def test_direct_requirements_still_enforces_the_gate():
    with pytest.raises(MeasurementIntegrityError):
        direct_requirements(_write("this is not a requirement at all\n"))


def main() -> int:
    tests = [(n, o) for n, o in sorted(globals().items())
             if n.startswith("test_") and callable(o)]
    failures = []
    for name, fn in tests:
        try:
            fn(); print("  PASS  {}".format(name))
        except Exception as exc:                        # noqa: BLE001
            failures.append(name); print("  FAIL  {}  {}".format(name, exc))
    print("\n  {} passed, {} failed".format(len(tests) - len(failures), len(failures)))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
