#!/usr/bin/env python
"""locate_conformal_artifacts.py (2026-07-10)

Read-only repo scan to LOCATE the artifacts conformal calibration needs and to clarify the
small meta_val=76 / meta_test=141 holdout. Answers, in one pass:

  1. Where is the per-model score matrix (oof_predictions or any *oof*/*pred*/*proba*/*score*)?
  2. Are 76/141 a smoke subset or the real holdout? (all meta_val/meta_test copies, sizes, mtimes)
  3. Which directory is authoritative? (full paths + modified times; newest highlighted)
  4. Does any predictions artifact carry PER-MODEL score columns vs a single ensemble prob?
  5. Is there a LARGER holdout anywhere? (all matching parquet by row count)

Excludes .venv / site-packages / .git. Guards every read; reports unreadable files (never
fails silently). No fixes -- diagnostic only.
"""
from __future__ import annotations

import os
import time
from pathlib import Path

try:
    import pandas as pd
except Exception as e:  # pragma: no cover
    print(f"FATAL: pandas import failed: {e}")
    raise SystemExit(2)

ROOT = Path(".").resolve()
EXCLUDE_DIRS = {".venv312", ".venv", "site-packages", ".git", "__pycache__", "node_modules"}
NAME_HINTS = ("oof", "pred", "proba", "prob", "score", "meta_", "y_val", "y_test",
              "x_val", "x_test", "calib", "holdout", "blend", "ensemble")
DATA_EXTS = {".parquet", ".pq"}


def _skip(path: Path) -> bool:
    return any(part in EXCLUDE_DIRS for part in path.parts)


def _fmt_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.0f}{unit}"
        n /= 1024
    return f"{n:.0f}TB"


def main():
    print("=" * 80)
    print(f"CONFORMAL ARTIFACT LOCATOR  (root: {ROOT})")
    print("=" * 80)

    hits = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for fn in filenames:
            p = Path(dirpath) / fn
            if _skip(p):
                continue
            low = fn.lower()
            if p.suffix.lower() in DATA_EXTS and any(h in low for h in NAME_HINTS):
                hits.append(p)

    if not hits:
        print("NO matching parquet artifacts found under the repo (excluding venv/git).")
        print("This itself is informative: the calibration artifacts are NOT on this machine at")
        print("the expected locations. They may need to be regenerated by re-running the pipeline.")
        return 0

    print(f"\nFound {len(hits)} candidate artifact file(s). Details (path | size | mtime | rows | cols):\n")
    rows_info = []
    for p in sorted(hits):
        rel = p.relative_to(ROOT)
        try:
            size = _fmt_size(p.stat().st_size)
            mtime = time.strftime("%Y-%m-%d %H:%M", time.localtime(p.stat().st_mtime))
        except Exception as e:
            print(f"  {rel}  [stat error: {e}]")
            continue
        try:
            df = pd.read_parquet(p)
            nrows, ncols = len(df), len(df.columns)
            rows_info.append((str(rel), nrows, ncols, mtime, list(df.columns)))
            print(f"  {rel}")
            print(f"      size {size} | mtime {mtime} | rows {nrows:,} | cols {ncols}")
        except Exception as e:
            print(f"  {rel}  [READ ERROR: {type(e).__name__}: {e}]")
    print()

    # ---- Q4: which artifacts look like SCORE matrices? (per-model columns) ----
    print("=" * 80)
    print("Q4. Score-matrix candidates (files whose columns look like model predictions):")
    print("=" * 80)
    model_tokens = ("xgb", "lgb", "light", "cat", "forest", "logistic", "nn", "mlp", "deep",
                    "mc_dropout", "kan", "gnn", "cnn", "ensemble", "blend", "stack", "proba",
                    "pred", "score", "p_path")
    score_candidates = []
    for rel, nrows, ncols, mtime, cols in rows_info:
        colcat = " ".join(c.lower() for c in cols)
        n_model_like = sum(1 for c in cols if any(t in c.lower() for t in model_tokens))
        if n_model_like >= 2 or "oof" in rel.lower():
            score_candidates.append((rel, nrows, ncols, n_model_like))
            print(f"  {rel}  (rows {nrows:,}, cols {ncols}, model-like cols {n_model_like})")
            print(f"      columns: {cols}")
    if not score_candidates:
        print("  NONE found. No artifact carries multiple model-prediction-like columns.")
        print("  => the per-model/ensemble SCORE matrix is not present under a scanned name.")
    print()

    # ---- Q2/Q3/Q5: holdout sizing ----
    print("=" * 80)
    print("Q2/Q3/Q5. Holdout sizing -- meta/y/X artifacts by row count (smoke vs full run?):")
    print("=" * 80)
    holdout = [(rel, nrows, ncols, mtime) for rel, nrows, ncols, mtime, cols in rows_info
               if any(k in rel.lower() for k in ("meta_", "y_val", "y_test", "x_val", "x_test"))]
    for rel, nrows, ncols, mtime in sorted(holdout, key=lambda r: -r[1]):
        print(f"  rows {nrows:>10,}  cols {ncols:>4}  mtime {mtime}  {rel}")
    if holdout:
        max_rows = max(h[1] for h in holdout)
        print(f"\n  LARGEST holdout artifact: {max_rows:,} rows.")
        if max_rows < 5000:
            print("  => ALL holdout artifacts are small (<5,000 rows). Consistent with a SMOKE/DEV")
            print("     run, NOT the full 4.4M-cohort run. Conformal on this would be valid but very")
            print("     wide; a full-run holdout is likely needed for meaningful calibration.")
        else:
            print("  => A larger holdout exists; prefer it for calibration.")
    print()
    print("=" * 80)
    print("LOCATE COMPLETE -- review before building calibrate.py against real scores.")
    print("=" * 80)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
